[package]
name = "atm_machine"
version = "0.1.0"
authors = ["David Chubabriya <31448563+davidc6@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
